<?php

/**
 * BaseContentObject
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $Id
 * @property integer $Pid
 * @property date $PublishStart
 * @property date $PublishEnd
 * @property string $ObjectType
 * @property integer $User_id
 * @property string $Content
 * @property string $Name
 * @property string $Address
 * @property string $Address2
 * @property string $City
 * @property string $Zip
 * @property string $Email
 * @property string $CCPNumber
 * @property string $Facebook
 * @property string $Twitter
 * @property string $Title
 * @property string $FbContentLink
 * @property string $FbImportDate
 * @property string $Description
 * @property string $Comment
 * @property integer $Post_Id
 * @property integer $Album_Id
 * @property integer $Photo_Id
 * @property integer $Mix_Id
 * @property string $Image
 * @property string $ImageThumb
 * @property integer $ImageHeight
 * @property integer $ImageWidth
 * @property integer $ImageThumbWidth
 * @property integer $ImageThumbHeight
 * @property integer $Artist_Id
 * @property string $Website
 * @property string $MySpace
 * @property string $ContactInfo
 * @property string $AudioUrl
 * @property date $Start
 * @property date $End
 * @property integer $EventLocation_Id
 * @property string $Phone
 * @property string $MapUrl
 * @property string $LocationImage
 * @property ContentObject $ContentObject
 * @property PtkUser $PtkUser
 * @property Doctrine_Collection $VisibilityRestriction
 * @property Doctrine_Collection $EditPermission
 * 
 * @method integer             getId()                    Returns the current record's "Id" value
 * @method integer             getPid()                   Returns the current record's "Pid" value
 * @method date                getPublishStart()          Returns the current record's "PublishStart" value
 * @method date                getPublishEnd()            Returns the current record's "PublishEnd" value
 * @method string              getObjectType()            Returns the current record's "ObjectType" value
 * @method integer             getUserId()                Returns the current record's "User_id" value
 * @method string              getContent()               Returns the current record's "Content" value
 * @method string              getName()                  Returns the current record's "Name" value
 * @method string              getAddress()               Returns the current record's "Address" value
 * @method string              getAddress2()              Returns the current record's "Address2" value
 * @method string              getCity()                  Returns the current record's "City" value
 * @method string              getZip()                   Returns the current record's "Zip" value
 * @method string              getEmail()                 Returns the current record's "Email" value
 * @method string              getCCPNumber()             Returns the current record's "CCPNumber" value
 * @method string              getFacebook()              Returns the current record's "Facebook" value
 * @method string              getTwitter()               Returns the current record's "Twitter" value
 * @method string              getTitle()                 Returns the current record's "Title" value
 * @method string              getFbContentLink()         Returns the current record's "FbContentLink" value
 * @method string              getFbImportDate()          Returns the current record's "FbImportDate" value
 * @method string              getDescription()           Returns the current record's "Description" value
 * @method string              getComment()               Returns the current record's "Comment" value
 * @method integer             getPostId()                Returns the current record's "Post_Id" value
 * @method integer             getAlbumId()               Returns the current record's "Album_Id" value
 * @method integer             getPhotoId()               Returns the current record's "Photo_Id" value
 * @method integer             getMixId()                 Returns the current record's "Mix_Id" value
 * @method string              getImage()                 Returns the current record's "Image" value
 * @method string              getImageThumb()            Returns the current record's "ImageThumb" value
 * @method integer             getImageHeight()           Returns the current record's "ImageHeight" value
 * @method integer             getImageWidth()            Returns the current record's "ImageWidth" value
 * @method integer             getImageThumbWidth()       Returns the current record's "ImageThumbWidth" value
 * @method integer             getImageThumbHeight()      Returns the current record's "ImageThumbHeight" value
 * @method integer             getArtistId()              Returns the current record's "Artist_Id" value
 * @method string              getWebsite()               Returns the current record's "Website" value
 * @method string              getMySpace()               Returns the current record's "MySpace" value
 * @method string              getContactInfo()           Returns the current record's "ContactInfo" value
 * @method string              getAudioUrl()              Returns the current record's "AudioUrl" value
 * @method date                getStart()                 Returns the current record's "Start" value
 * @method date                getEnd()                   Returns the current record's "End" value
 * @method integer             getEventLocationId()       Returns the current record's "EventLocation_Id" value
 * @method string              getPhone()                 Returns the current record's "Phone" value
 * @method string              getMapUrl()                Returns the current record's "MapUrl" value
 * @method string              getLocationImage()         Returns the current record's "LocationImage" value
 * @method ContentObject       getContentObject()         Returns the current record's "ContentObject" value
 * @method PtkUser             getPtkUser()               Returns the current record's "PtkUser" value
 * @method Doctrine_Collection getVisibilityRestriction() Returns the current record's "VisibilityRestriction" collection
 * @method Doctrine_Collection getEditPermission()        Returns the current record's "EditPermission" collection
 * @method ContentObject       setId()                    Sets the current record's "Id" value
 * @method ContentObject       setPid()                   Sets the current record's "Pid" value
 * @method ContentObject       setPublishStart()          Sets the current record's "PublishStart" value
 * @method ContentObject       setPublishEnd()            Sets the current record's "PublishEnd" value
 * @method ContentObject       setObjectType()            Sets the current record's "ObjectType" value
 * @method ContentObject       setUserId()                Sets the current record's "User_id" value
 * @method ContentObject       setContent()               Sets the current record's "Content" value
 * @method ContentObject       setName()                  Sets the current record's "Name" value
 * @method ContentObject       setAddress()               Sets the current record's "Address" value
 * @method ContentObject       setAddress2()              Sets the current record's "Address2" value
 * @method ContentObject       setCity()                  Sets the current record's "City" value
 * @method ContentObject       setZip()                   Sets the current record's "Zip" value
 * @method ContentObject       setEmail()                 Sets the current record's "Email" value
 * @method ContentObject       setCCPNumber()             Sets the current record's "CCPNumber" value
 * @method ContentObject       setFacebook()              Sets the current record's "Facebook" value
 * @method ContentObject       setTwitter()               Sets the current record's "Twitter" value
 * @method ContentObject       setTitle()                 Sets the current record's "Title" value
 * @method ContentObject       setFbContentLink()         Sets the current record's "FbContentLink" value
 * @method ContentObject       setFbImportDate()          Sets the current record's "FbImportDate" value
 * @method ContentObject       setDescription()           Sets the current record's "Description" value
 * @method ContentObject       setComment()               Sets the current record's "Comment" value
 * @method ContentObject       setPostId()                Sets the current record's "Post_Id" value
 * @method ContentObject       setAlbumId()               Sets the current record's "Album_Id" value
 * @method ContentObject       setPhotoId()               Sets the current record's "Photo_Id" value
 * @method ContentObject       setMixId()                 Sets the current record's "Mix_Id" value
 * @method ContentObject       setImage()                 Sets the current record's "Image" value
 * @method ContentObject       setImageThumb()            Sets the current record's "ImageThumb" value
 * @method ContentObject       setImageHeight()           Sets the current record's "ImageHeight" value
 * @method ContentObject       setImageWidth()            Sets the current record's "ImageWidth" value
 * @method ContentObject       setImageThumbWidth()       Sets the current record's "ImageThumbWidth" value
 * @method ContentObject       setImageThumbHeight()      Sets the current record's "ImageThumbHeight" value
 * @method ContentObject       setArtistId()              Sets the current record's "Artist_Id" value
 * @method ContentObject       setWebsite()               Sets the current record's "Website" value
 * @method ContentObject       setMySpace()               Sets the current record's "MySpace" value
 * @method ContentObject       setContactInfo()           Sets the current record's "ContactInfo" value
 * @method ContentObject       setAudioUrl()              Sets the current record's "AudioUrl" value
 * @method ContentObject       setStart()                 Sets the current record's "Start" value
 * @method ContentObject       setEnd()                   Sets the current record's "End" value
 * @method ContentObject       setEventLocationId()       Sets the current record's "EventLocation_Id" value
 * @method ContentObject       setPhone()                 Sets the current record's "Phone" value
 * @method ContentObject       setMapUrl()                Sets the current record's "MapUrl" value
 * @method ContentObject       setLocationImage()         Sets the current record's "LocationImage" value
 * @method ContentObject       setContentObject()         Sets the current record's "ContentObject" value
 * @method ContentObject       setPtkUser()               Sets the current record's "PtkUser" value
 * @method ContentObject       setVisibilityRestriction() Sets the current record's "VisibilityRestriction" collection
 * @method ContentObject       setEditPermission()        Sets the current record's "EditPermission" collection
 * 
 * @package    poomtshak
 * @subpackage model
 * @author     PoUpA
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContentObject extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('content_object');
        $this->hasColumn('Id', 'integer', 255, array(
             'primary' => true,
             'unique' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 255,
             ));
        $this->hasColumn('Pid', 'integer', 255, array(
             'type' => 'integer',
             'length' => 255,
             ));
        $this->hasColumn('PublishStart', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('PublishEnd', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('ObjectType', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('User_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Content', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             'notnull' => true,
             ));
        $this->hasColumn('Name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             'notnull' => true,
             ));
        $this->hasColumn('Address', 'string', 3000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 3000,
             ));
        $this->hasColumn('Address2', 'string', 3000, array(
             'type' => 'string',
             'length' => 3000,
             ));
        $this->hasColumn('City', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('Zip', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('Email', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('CCPNumber', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('Facebook', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('Twitter', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('Title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             'unique' => true,
             ));
        $this->hasColumn('FbContentLink', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('FbImportDate', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('Description', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             'notnull' => true,
             ));
        $this->hasColumn('Comment', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('Post_Id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Album_Id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Photo_Id', 'integer', null, array(
             'type' => 'integer',
             'unique' => true,
             ));
        $this->hasColumn('Mix_Id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Image', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('ImageThumb', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('ImageHeight', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ImageWidth', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ImageThumbWidth', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ImageThumbHeight', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Artist_Id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Website', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('MySpace', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('ContactInfo', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('AudioUrl', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('Start', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('End', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('EventLocation_Id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Phone', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('MapUrl', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('LocationImage', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->setSubClasses(array(
             'MasterPage' => 
             array(
              'ObjectType' => 'MasterPage',
             ),
             'Contact' => 
             array(
              'ObjectType' => 'Contact',
             ),
             'Post' => 
             array(
              'ObjectType' => 'Post',
             ),
             'PostCategory' => 
             array(
              'ObjectType' => 'PostCategory',
             ),
             'Comment' => 
             array(
              'ObjectType' => 'Comment',
             ),
             'Album' => 
             array(
              'ObjectType' => 'Album',
             ),
             'Photo' => 
             array(
              'ObjectType' => 'Photo',
             ),
             'Artist' => 
             array(
              'ObjectType' => 'Artist',
             ),
             'Mix' => 
             array(
              'ObjectType' => 'Mix',
             ),
             'Event' => 
             array(
              'ObjectType' => 'Event',
             ),
             'EventLocation' => 
             array(
              'ObjectType' => 'EventLocation',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ContentObject', array(
             'local' => 'Pid',
             'foreign' => 'Id'));

        $this->hasOne('PtkUser', array(
             'local' => 'User_id',
             'foreign' => 'id'));

        $this->hasMany('VisibilityRestriction', array(
             'local' => 'Id',
             'foreign' => 'ContentObject_Id'));

        $this->hasMany('EditPermission', array(
             'local' => 'Id',
             'foreign' => 'ContentObject_Id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}