<?php

/**
 * BaseAlbum
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Doctrine_Collection $Comment
 * @property Doctrine_Collection $AlbumPhoto
 * 
 * @method Doctrine_Collection getComment()    Returns the current record's "Comment" collection
 * @method Doctrine_Collection getAlbumPhoto() Returns the current record's "AlbumPhoto" collection
 * @method Album               setComment()    Sets the current record's "Comment" collection
 * @method Album               setAlbumPhoto() Sets the current record's "AlbumPhoto" collection
 * 
 * @package    poomtshak
 * @subpackage model
 * @author     PoUpA
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAlbum extends ContentObject
{
    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Comment', array(
             'local' => 'id',
             'foreign' => 'Album_Id'));

        $this->hasMany('AlbumPhoto', array(
             'local' => 'id',
             'foreign' => 'Album_Id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}