<?php

/**
 * BaseEditPermission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $Id
 * @property integer $ContentObject_Id
 * @property integer $UserGroup_id
 * @property ContentObject $ContentObject
 * @property UserGroup $UserGroup
 * 
 * @method integer        getId()               Returns the current record's "Id" value
 * @method integer        getContentObjectId()  Returns the current record's "ContentObject_Id" value
 * @method integer        getUserGroupId()      Returns the current record's "UserGroup_id" value
 * @method ContentObject  getContentObject()    Returns the current record's "ContentObject" value
 * @method UserGroup      getUserGroup()        Returns the current record's "UserGroup" value
 * @method EditPermission setId()               Sets the current record's "Id" value
 * @method EditPermission setContentObjectId()  Sets the current record's "ContentObject_Id" value
 * @method EditPermission setUserGroupId()      Sets the current record's "UserGroup_id" value
 * @method EditPermission setContentObject()    Sets the current record's "ContentObject" value
 * @method EditPermission setUserGroup()        Sets the current record's "UserGroup" value
 * 
 * @package    poomtshak
 * @subpackage model
 * @author     PoUpA
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEditPermission extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('edit_permission');
        $this->hasColumn('Id', 'integer', null, array(
             'primary' => true,
             'unique' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('ContentObject_Id', 'integer', 255, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('UserGroup_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ContentObject', array(
             'local' => 'ContentObject_Id',
             'foreign' => 'Id'));

        $this->hasOne('UserGroup', array(
             'local' => 'UserGroup_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}