<?php

/**
 * BaseComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Post $Post
 * @property Album $Album
 * @property Photo $Photo
 * @property Mix $Mix
 * 
 * @method Post    getPost()  Returns the current record's "Post" value
 * @method Album   getAlbum() Returns the current record's "Album" value
 * @method Photo   getPhoto() Returns the current record's "Photo" value
 * @method Mix     getMix()   Returns the current record's "Mix" value
 * @method Comment setPost()  Sets the current record's "Post" value
 * @method Comment setAlbum() Sets the current record's "Album" value
 * @method Comment setPhoto() Sets the current record's "Photo" value
 * @method Comment setMix()   Sets the current record's "Mix" value
 * 
 * @package    poomtshak
 * @subpackage model
 * @author     PoUpA
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseComment extends ContentObject
{
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Post', array(
             'local' => 'Post_Id',
             'foreign' => 'id'));

        $this->hasOne('Album', array(
             'local' => 'Album_Id',
             'foreign' => 'id'));

        $this->hasOne('Photo', array(
             'local' => 'Photo_Id',
             'foreign' => 'id'));

        $this->hasOne('Mix', array(
             'local' => 'Mix_Id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}