<?php

/**
 * BaseMix
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Artist $Artist
 * @property Doctrine_Collection $Comment
 * @property Doctrine_Collection $Track
 * 
 * @method Artist              getArtist()  Returns the current record's "Artist" value
 * @method Doctrine_Collection getComment() Returns the current record's "Comment" collection
 * @method Doctrine_Collection getTrack()   Returns the current record's "Track" collection
 * @method Mix                 setArtist()  Sets the current record's "Artist" value
 * @method Mix                 setComment() Sets the current record's "Comment" collection
 * @method Mix                 setTrack()   Sets the current record's "Track" collection
 * 
 * @package    poomtshak
 * @subpackage model
 * @author     PoUpA
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMix extends ContentObject
{
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Artist', array(
             'local' => 'Artist_Id',
             'foreign' => 'id'));

        $this->hasMany('Comment', array(
             'local' => 'id',
             'foreign' => 'Mix_Id'));

        $this->hasMany('Track', array(
             'local' => 'id',
             'foreign' => 'Mix_Id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}