<?php

/**
 * BaseEvent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Photo $Photo
 * @property EventLocation $EventLocation
 * @property Doctrine_Collection $ArtistEvent
 * 
 * @method Photo               getPhoto()         Returns the current record's "Photo" value
 * @method EventLocation       getEventLocation() Returns the current record's "EventLocation" value
 * @method Doctrine_Collection getArtistEvent()   Returns the current record's "ArtistEvent" collection
 * @method Event               setPhoto()         Sets the current record's "Photo" value
 * @method Event               setEventLocation() Sets the current record's "EventLocation" value
 * @method Event               setArtistEvent()   Sets the current record's "ArtistEvent" collection
 * 
 * @package    poomtshak
 * @subpackage model
 * @author     PoUpA
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEvent extends ContentObject
{
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Photo', array(
             'local' => 'Photo_Id',
             'foreign' => 'id'));

        $this->hasOne('EventLocation', array(
             'local' => 'EventLocation_Id',
             'foreign' => 'id'));

        $this->hasMany('ArtistEvent', array(
             'local' => 'id',
             'foreign' => 'Event_Id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}