<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/02/04 19:26:15

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=poomtshak',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
