<?php

/**
 * AlbumPhotoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AlbumPhotoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AlbumPhotoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AlbumPhoto');
    }
}