<?php

/**
 * ArtistEventTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArtistEventTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ArtistEventTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ArtistEvent');
    }
}