<?php

/**
 * ArtistTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArtistTable extends ContentObjectTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ArtistTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Artist');
    }
}