<?php

/**
 * ContentObjectTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContentObjectTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContentObjectTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ContentObject');
    }
}