<?php

/**
 * EditPermissionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EditPermissionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EditPermissionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EditPermission');
    }
}