<?php

/**
 * EventLocationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EventLocationTable extends ContentObjectTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object EventLocationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EventLocation');
    }
}