<?php

/**
 * MixTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MixTable extends ContentObjectTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object MixTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Mix');
    }
}