<?php

/**
 * PostPostCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PostPostCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PostPostCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PostPostCategory');
    }
}