<?php

/**
 * PtkUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PtkUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PtkUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PtkUser');
    }
}