<?php

/**
 * VisibilityRestrictionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VisibilityRestrictionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VisibilityRestrictionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VisibilityRestriction');
    }
}