<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/02/21 22:40:22

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=poomtshakorg',
  'username' => 'root',
  'password' => 'link64',
  'name' => 'doctrine',
)),);
