<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/02/18 13:47:01

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=poomtshakorg',
  'username' => 'root',
  'password' => 'link64',
  'name' => 'doctrine',
)),);
